
var __cov_WrOYDmP5CNRVbFFtjIi9ww = (Function('return this'))();
if (!__cov_WrOYDmP5CNRVbFFtjIi9ww.__coverage__) { __cov_WrOYDmP5CNRVbFFtjIi9ww.__coverage__ = {}; }
__cov_WrOYDmP5CNRVbFFtjIi9ww = __cov_WrOYDmP5CNRVbFFtjIi9ww.__coverage__;
if (!(__cov_WrOYDmP5CNRVbFFtjIi9ww['test/helper.js'])) {
   __cov_WrOYDmP5CNRVbFFtjIi9ww['test/helper.js'] = {"path":"test/helper.js","s":{"1":0,"2":0,"3":0,"4":0,"5":0,"6":0,"7":0},"b":{},"f":{"1":0,"2":0,"3":0},"fnMap":{"1":{"name":"(anonymous_1)","line":8,"loc":{"start":{"line":8,"column":19},"end":{"line":8,"column":30}}},"2":{"name":"(anonymous_2)","line":10,"loc":{"start":{"line":10,"column":33},"end":{"line":10,"column":43}}},"3":{"name":"(anonymous_3)","line":12,"loc":{"start":{"line":12,"column":57},"end":{"line":12,"column":68}}}},"statementMap":{"1":{"start":{"line":8,"column":0},"end":{"line":21,"column":3}},"2":{"start":{"line":9,"column":4},"end":{"line":9,"column":56}},"3":{"start":{"line":10,"column":4},"end":{"line":20,"column":7}},"4":{"start":{"line":12,"column":8},"end":{"line":18,"column":11}},"5":{"start":{"line":14,"column":12},"end":{"line":14,"column":70}},"6":{"start":{"line":15,"column":12},"end":{"line":15,"column":50}},"7":{"start":{"line":17,"column":12},"end":{"line":17,"column":80}}},"branchMap":{}};
}
__cov_WrOYDmP5CNRVbFFtjIi9ww = __cov_WrOYDmP5CNRVbFFtjIi9ww['test/helper.js'];
__cov_WrOYDmP5CNRVbFFtjIi9ww.s['1']++;describe('Helper',function(){__cov_WrOYDmP5CNRVbFFtjIi9ww.f['1']++;__cov_WrOYDmP5CNRVbFFtjIi9ww.s['2']++;var DateHelper=require('../Helper/dateFormatter');__cov_WrOYDmP5CNRVbFFtjIi9ww.s['3']++;describe('Date Formatter: ',function(){__cov_WrOYDmP5CNRVbFFtjIi9ww.f['2']++;__cov_WrOYDmP5CNRVbFFtjIi9ww.s['4']++;it('Should Return current MySQL formatted Date',function(){__cov_WrOYDmP5CNRVbFFtjIi9ww.f['3']++;__cov_WrOYDmP5CNRVbFFtjIi9ww.s['5']++;var javascriptDate=new Date(2015,5,5,16,30,20,0);__cov_WrOYDmP5CNRVbFFtjIi9ww.s['6']++;var mySQLDate='2015-06-05 16:30:20';__cov_WrOYDmP5CNRVbFFtjIi9ww.s['7']++;expect(DateHelper.getFormattedDate(javascriptDate)).toBe(mySQLDate);});});});
